apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: task-timer-certificate
  namespace: {{ namespace }}
spec:
  secretName: task-timer-tls
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - {{ hostname }}