apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-timer-deployment
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: task-timer
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: task-timer
        branch: {{ git_branch }}
    spec:
      containers:
        - name: task-timer-container
          image: ruchira088/task-timer:{{ git_branch }}-{{ git_commit }}
          envFrom:
            - configMapRef:
                name: task-timer-data-config-map
            - secretRef:
                name: task-timer-secrets
          readinessProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-readiness-probe
          livenessProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-liveness-probe
          startupProbe:
            periodSeconds: 5
            failureThreshold: 5
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-startup-probe
          ports:
            - name: http4s-port
              containerPort: 8000
          volumeMounts:
            - mountPath: /opt/data
              name: file-config-map
      volumes:
        - name: file-config-map
          configMap:
            name: task-timer-file-config-map

