version: "3.8"

services:

  task-timer:
    image: task-timer:latest
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: jdbc:postgresql://postgresql:5432/task-timer
      DATABASE_USER: admin
      DATABASE_PASSWORD: password

  postgresql:
    image: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d task-timer" ]
      start_period: 5s
      interval: 5s
      timeout: 2s
    environment:
      POSTGRES_DB: task-timer
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password