version: "3.8"

services:

  task-timer:
#    build: .
    image: task-timer:latest
    ports:
      - 8000:8000
#      - 5005:5005
    volumes:
      - "./src/main/resources/logback.xml:/opt/data/logback.xml"
#      - "~/.sbt:/root/.sbt"
#      - "~/Library/Caches/Coursier:/root/.cache/coursier" # MacOS Coursier cache
#      #      - "~/.cache/coursier:/root/.cache/coursier" # Linux Coursier cache
#      #      - "~/AppData/Local/Coursier/Cache:/root/.cache/coursier" # Windows Coursier cache
#      - ".:/opt/task-timer"
#      - "/opt/task-timer/target"
#      - "/opt/task-timer/project/target"
#      - "/root/.sbt/1.0/plugins"
