FROM openjdk:17-slim

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/task-timer

ADD task-timer-*.tgz .

EXPOSE 8000

CMD [ "/opt/task-timer/bin/task-timer" ]
